### ISSUE TITLE
Singalese texts

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#123]
From email 20/7/2015:
Ven Mettavihari: senior monk in Colombo, founder of metta.lk, and helping us obtain the latest files for Sinhala texts.
Janaka (Path to Nirvana): runs http://pitaka.lk/. Janaka has received the pdf files of the Sinhala translations from Godage, the publisher. These are the corrected and completed text of the AP de Zoysa translation, which is the same translation as on metta.lk and on SC. Janaka will extract the text of the pdfs, convert to Unicode, and prepare XML for his site. Once this is done we can easily convert for SC.

In addition, I will mention Andrew Glass. He is an accomplished Indologist, who helped develop Unicode standards and fonts for Gandhari, and is working for Microsoft in the area of support for Indic scripts. He is happy to help if we have any issues regarding Unicode conversion or similar issues.

So the main thing at the moment is for Janaka. When ready, he will let Vimala know so she can do the conversion to SC.

**Comment by sujato** [comment]
Janaka has now mainly completed preparing these files, so Blake or Vimala can look at preparing a script to adapt them for SC.

**Comment by ghost** [comment]
Will have a look at it. Can you let me know if it is his whole website that needs to be done or just the part we do not have on SC yet?

**Comment by blake-sc** [comment]
Sounds good. Create a script under suttacentral/utility/sinhalese or something and add it to git.

I have noticed you can also get the pali and translation side by side with parallel files on pitaka.lk, at some stage I'd like to look into making automated links between the translation and pali on SuttaCentral, since the pali on pitaka.lk is (presumably) different to the pali on SuttaCentral this wont be completely straightforward, but we do have the edition paragraph number correspondence data from mahasangiti and the palis should be similar enough (once transliterated from sinhalese script using Yuttadhammo's code) to support fuzzy matching in most cases.

**Comment by sujato** [comment]
@SamaneriVimala: we need to do the whole thing. This is a revised edition of the same translation we have. Our digitized text was created from the original print edition, typed by volunteers organized by Bhante Mettavihari. It has several incomplete sections, and I believe the typing quality is not great. The new edition is based on a revised print edition recently published in Sri Lanka by Godage's, for which we obtained permission via Kumari Jayawardhana. She is the daughter of the AP de Zoysa, who originally organized the translation project. (The translation is usually called the de Zoysa translation, although in fact he organized and sponsored a group of monks to do it, many of whom later worked on the Buddha Jayanthi edition.) She is also a leading third-wave feminist scholar, and as it happens was a classmate of one of my supporters in Sydney (Amaradasa Liyanagamage; you might remember his daughter Rumi and their family.) We assume that the new edition is corrected and of good quality, although I don't know of anyone who has checked this carefully. In any case, it will certainly be better than what we have currently. Since the text is extracted from PDF, it is not easy to get it right, but Janaka is doing a great job.

As for automating translation and text on SC, @blake-sc , can you give more details what you have in mind? When the new translation is done, of course this will be possible, and extensible to other languages. Did you mean something else? I'm not convinced that it will be worth putting a huge amount of effort into legacy translations. But if it's simple, then why not?

**Comment by blake-sc** [comment]
Well on pitaka.lk, there is already the side-by-side view with the pali and translation, even though the pali editions aren't identical, this gives us virtually all the data we need to say what pali the translation refers to.

We have the ms pali edition concordance (tables/pali_concord.csv) which maps the ms_paragraph to other editions.

For example, taking the end of DN13, on pitaka.lk, the final paragraphs (in the pali) have 

``` xml
<pb ed="V" n="1.0227"></pb>
<pb ed="T" n="1.0312"></pb>
<pb ed="M" n="1.0236"></pb>
```

While in pali_concord.csv, at the end of 6d in the ms paragraphs 955-956, these seem to relate respectively to:
vp 1.227 (p_6D_955)
s3  9.312 (p_6D_955)
c1/c2 6.236 (p_6D_956)

Because on pitaka.lk the pali and translation are side by side, we can simply transfer those pali paragraph numbers from the pali into the translation, we can then lookup in pali_concord to find the ms paragraph number (note: I actually have some python code which makes this lookup very straightforward), and at the end of the day we can say that this paragraph of Sinhalese translation, refers to this paragraph of pali in the ms edition. While the mapping is a little bit crude because the data in pali_concord.csv is only accurate to the page level, it can still take you to about the right place.
We could even have it automatically trigger the conversion to Sinhalese script if coming from the Sinhalese translation.

(Also speaking of the pali_concord data, I really should use it to insert the s1 text_images into our pali texts, I've been putting it off, but now I've refreshed my knowledge of the pali_concord data it wont be very difficult at all)

**Comment by sujato** [comment]
okay, that all sounds great.

Incidentally, did you see the js clipboard I sheared earlier:
https://github.com/zenorocha/clipboard.js

Hopefully it can replace flash... which, BTW, I don't have, so I can't use
the ref selector thingy.

**Comment by ghost** [comment]
Just to keep a record of this.
See email to Bhante Sujato from the developers of the site http://www.thripitakaya.org/ 
They ask for their translations to be included in SC. 
Bhante answered that on the internationalised site it will be possible to include multiple translations. (16 jan 2016)

**Comment by sujato** [comment]
I believe that we have not yet updated the texts from pitaka.lk, either Vimala or Blake, can you look into this when you get a chance?

**Comment by ghost** [comment]
The texts are done. I left the msdiv numbers in it and created an exception to the css so the numbers show when Textual Details are clicked. Leaving the rest up to @blake-sc.

**Comment by ghost** [comment]
I think @blake-sc still wanted to do something with these texts. Also, some texts are still from the wrong source and Aruna is working on this.

**Comment by sujato** [comment]
Oops!
