### ISSUE TITLE
Integrate cross-references from MS pali text as parallels

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#131]
Our concept of parallels includes parallels within a corpus, such as Pali>Pali. There's approx 3522 such parallels marked class="cross" in our Pali text. It would be great if these could be added to our parallel tables. There would be some complexities to this:
- Some cross references will already be in our tables, so we need to filter out duplicate IDs.
- In some cases (mainly in AN and SN, but also elsewhere) the sutta numbering has changed, so this needs to be systematically checked. We need to ensure that each cross-reference actually points to the right text.
- In some cases the references will be to part of a sutta. This should be noted and, if possible, our "embedded parallel" markup used to identify the exact passage.

**Comment by blake-sc** [comment]
The correspondences are always ms_paragraph->ms_paragraph this leaves no chance of getting the sutta numbering wrong.

I think it's probably worthwhile having a different class of parallel for these cross references, even if we decide not to visually distinguish them from other kind of parallels (perhaps display them as partial), it would be good to segregate them in our data. My experience in working with the ms variant notes and cross references is they tended to be kind of loose in how they used them, rather like the SuttaCentral partial parallel.

Another thing in favor of handling them differently is we don't want to loose information, these notes are already defined in terms of a correspondence between two paragraph numbers. The way we handle "embedded parallels" is somewhere between really clunky and absolutely horrible because every embedded parallel requires a new sutta to be defined (ugh!), and it makes a lot of sense to maintain these cross references in the data as a relationship between two paragraphs.

Ideally I'd like to supplant embedded parallels with a new-style parallel mapping defined in terms of 
`uid#start_p-end_p ↔ uid#start_p-end_p`
then a little bit of javascript magic (or even python magic, but I prefer javascript) could throw some markup around those paragraphs  (they become normal parallels for the parallel pages). The idea of start_p-end_p is you can define a paragraph range, but if you omit end_p it should be treated as a "point reference" which is ambiguous with respect to paragraph range. If you genuinely intend it to refer to that and only that paragraph, the paragraph number should be doubled up: uid:start_p-start_p, indicating the reference both starts and ends at that paragraph.
A paragraph-range reference would be displayed like an embedded parallel, wrapping the relevant paragraphs. While a paragraph point reference would need to be displayed as an arrow, line or other "1-dimensional" shape.
Note that the new-style parallel mapping would be fully capable of defining existing parallels, it just doesn't define any paragraph numbers at all.

**Comment by sujato** [comment]
On Mon, 19 Oct 2015 at 20:00 Blake Walsh notifications@github.com wrote:

> The correspondences are always ms_paragraph->ms_paragraph this leaves no
> chance of getting the sutta numbering wrong.

Oh, great, this had been nagging me for some time, but I never looked into
it.

**Comment by blake-sc** [comment]
> Sounds fine, but what to do when the embedded parallel doesn't map onto
> paragraph divisions? This is the case with some of our Chinese texts, which
> have very long paragraphs, i.e. chapters long. Would we just leave these
> as-is? But then we have two different systems for doing the same thing...

Well for the time being the new-style parallel definition can co-exist with the old way.

However my idea is that while I speak of "paragraphs", it's actually a mapping between elements with ids, so you could just use the CBETA line numbers, while those are intra-paragraph ids, that would be no obstacle to the javascript magic, it could just have special handling for that case.

**Comment by ghost** [comment]
Can this issue be closed?
