### ISSUE TITLE
Navigation errors

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#143]
The link of the 'next' arrow button on the last page of English Khuddakapatha (Kp9)
is https://suttacentral.net/None/dhp1#12 which leads nowhere, while there's a working URL of https://suttacentral.net/en/dhp#1

Absent are 'previous'/'next' buttons on the page of English Dhammapada (Dhp423)

and instead of the Dhammapada as a title, None appears here in the link tooltip after the link is clicked

**Comment by blake-sc** [comment]
Hmmm, texts should never have embedded next/prev anchors - instead these are to be generated automatically using an algorthim which looks at uids and positions within divisions, or, in the case of desperation when the algorithm can't possibly guess which comes next (I don't know if this is still the case, since at some point I improved it to make better use of division and subdivision data), it is possible to define attributes on the html element as in: 
`<html data-prev="pi-tv-bi-vb-pj7" data-next="pi-tv-bi-vb-ss1">`

So in this case the bug is simply that some texts have the next/prev links hardcoded as anchors, and these should be purged.

**Comment by ghost** [comment]
True, but KP9 doesn't have any hardcoded embedded next/prev anchors as far as I can see. The same error appears on kp9.html in all the other languages (not just English). So that does not solve the problem.

I did a search and there were still some hardcoded ones on other suttas and have removed those. But this issue of course remains.

As a separate - but maybe related - issue: the language button in the sidebar of DHP in all languages does now work.

**Comment by ghost** [comment]
Same problem occurs at https://suttacentral.net/skt/skt-mu-kd17
I tried setting `<html data-next="">` on that one but that did not help.

**Comment by ghost** [comment]
The part relating to the dhp language-dropdown of this issue is now solved (https://discourse.suttacentral.net/t/language-list-error-in-dhammapada-menu/2995/1) but not the rest. On KP9 the NEXT link is still to: https://suttacentral.net/None/dhp1#1 and on UD1.1 the PREV link is to: https://suttacentral.net/None/dhp423#423.
The DHP itself does not have any more NEXT and PREV buttons.

**Comment by sujato** [comment]
I"m closing this as it will probably not apply to our new version, and we can expect a range of new bugs!
