### ISSUE TITLE
Incorrect display of refs in Vibhanga

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#162]
At https://suttacentral.net/en/vb7 the text refs don't display properly. Not sure if the problem extends further than this.

**Comment by ghost** [comment]
That is because BA and PTS-S are not defined. I take it that BA stands for "Paragraph numbers in The Book of Analysis" and what should the mouseover text be for PTS-S?

Another issue here is that in the Metadata it says:
`....The full text together with introduction is available on our Downloads page....`
and
`... A list of changes may be found in the Preface to the SuttaCentral edition on the Downloads page. ...`

And there is nothing on the Downloads page.

**Comment by sujato** [comment]
Actually I just checked this at https://suttacentral.net/en/vb1 

There it works, there must be a difference in the markup of the tags. But it does reveal, yes BA is "Book of Analysis". PTS s  must be "Pali Text Society section number." However it is incorrectly labelled as "vol/page", so that should be changed universally, as well as correcting the markup where necessary.

Will check for full file.

**Comment by ghost** [comment]
It works because I changed it this morning. 
I will change the mouseover text for PTS-S as well. The incorrect labelling was just something I did this morning while waiting for your reply.

**Comment by ghost** [comment]
OK. All done. The reason you might see vb7 still wrong is probably your browser cache. 
Still remains the issue with the meta data.

**Comment by sujato** [comment]
Okay, that's all good, thanks.

Please remove the metadata remarks for downloads and preface. i have added the introduction to Discourse. As for the Preface, I can't find it. if I do, I'll put it on Discourse, too.
