### ISSUE TITLE
weird firefox display bug when using chinese lookup

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#167]
In Firefox, when you use the chinese-english lookup, the next/prev links at the bottom of the page jump up and down.

**Comment by blake-sc** [comment]
I figured out the cause. The popup element is actually created at the end of the section - the reason for creating it outside the text is so it doesn't get "corrupted" by inherited text styles like headings or bold. It is position relative, and that moves it outside the usual page flow. Firefox still allocates space for it at the end of the section (even though it's not located there), Chrome does not.

I'll fix it by wrapping it in a position: absolute element, which suffices to convince Firefox that the element is really not participating in the normal page flow.

**Comment by sujato** [comment]
Well, that explains it. I tried to figure out what was happening with the display, but couldn't.

But this seems like a heavy-handed solution, and one which invites such glitches. Surely it's better to just nix any inherited styles in the popup? 

Also, do we use the same approach in the tables? Is this the reason for the FF/Chrome inconsistencies there, or is that something else?

**Comment by blake-sc** [comment]
This approach is far more robust, because there are so many possible styles that could be inherited especially when you consider the same code is reused on pootle and in principle elsewhere. It's also a tidy solution to ensuring the text size is consistent with the page as a whole (I know you could use px or rem size, but you don't actually know what the px or rem size of the page is so it wont work properly unless the page is remcentric). This approach also helps simplify things when nudging the position of the popup to adapt to smaller screens.

**Comment by sujato** [comment]
The problem is still occurring.
