### ISSUE TITLE
SuttaCentral SEO improvements

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#171]
I had a chat with someone the other day about SEO, and while I believe Google when they say not to worry about it, just build a good site, still I thought I'd throw SC at a few SEO testers and see what came up. Some of the suggestions seemed sensible and I'll add them here.
1. Include keywords in meta-title or description.
2. Include xml sitemap. https://support.google.com/webmasters/answer/183668 
3. IP canonicalization: Your site's IP 104.25.120.17 does not redirect to your site's domain name. This could cause duplicate content problems if a search engine indexes your site under both its IP and domain name. (But another site passed us on this)
4. Your server appears to allow access from User-agent Libwww-perl.
5. Use HTML Microdata Schema
6. The URL https://suttacentral.net/sutta_numbering is apparently disliked, as Google prefers hyphens to underscores. A trivial matter, but good to know.
7. Meta description should have fewer than 160 words.
8. Search form has fields without LABEL elements or TITLE attributes. This is a usability issue for screen readers.
9. `<div id="epigraph-store" type="text/html" style="display:none">`: Attribute 'type' not allowed on element. 
10. Too many `<h1>` elements and not enough text contrast in headings has been flagged.
11. Next/prev buttons have duplicated classes, i.e. `<a class="button" class="previous"`
12. We don't comply with the (ridiculous) EU policy on cookies. I wouldn't want to do this unless forced to, but if we could avoid cookies as far as possible that would be good. The same goes for privacy policy on web server logs.
13. Lack of "src" in home page images has been flagged. I presume this is to do with the lazy loading of images.

**Comment by blake-sc** [comment]
1. (keywords), 7 (meta description) - to be good it really needs to be done by a human. What we currently use is pretty lame.
2. xml sitemap. I've thought of this before. I really doubt it's helpful, as suttacentral pages are really well linked. The only thing which it might help with is preventing crawlers getting lost in vinaya parallels and not crawling important pages (like english translations of important suttas) at all.
3. Well usually our server's IP address is hidden behind Cloudlfare and if you attempt to access the site by IP address nginx responds with a nice polite 502 error, because it only responds if the request was to suttacentral.net (or something else in its rules), so the site which gave us a pass got it correct. Serving pages on a bare IP address is plain silly.
4. Irrelevant as far as I can tell, any badly behaved crawler will just set the User-agent as firefox or something.
5. We've looked into microdata before, usually isn't a good fit for our content, we could investigate again.
6. Good to know.
7. 
8. Huh, that could be worth fixing.
9. Looks like some whales with legs type issue.
10. I guess they only want a single h1 heading. I do find it odd we're using headings in the panel and possible the header as a whole. Are they really "headings" in the sense meant in HTML?
11. Man that never dies, it's due to stuff which is in the text HTML files but shouldn't be because it's generated dynamically.
12. The best summary I found is http://ec.europa.eu/ipg/basics/legal/cookies/index_en.htm and the list "Cookies clearly exempt from consent" includes "user interface customization" which is basically what we store data on in the user's browser for - it might be a tiny bit of a stretch, but we don't ever send anything which is stored back to our server, in this sense it's nothing even a little bit like tracking.
13. Yup. It possibly presents an issue for Google Image search, although a smart crawler would probably recognize lazy-loading syntax.

**Comment by sujato** [comment]
1. If I get time I'll write something for the home page at least.
2. up to you, but it seems easy enough to do. Google does recommend it, but like you say, we're well structured anyway.
3.   
4. I don't know, but at least some people say it saves botnet bandwidth. I wonder if it's a "nigerian prince" strategy. By making attacks deliberately primitive they filter out well-maintained sites and go straight for the idiots …
5. I'll have a look sometime.
6.   
7.   
8.   
9.   
10. Well, on the one hand it's a lot of headings and on the other hand, it's beacuase we have a well-structured menu that serves the whole site. I don't think it's a huge issue, but we might want to see if an alternative HTML is more clear.
11.   
12. Good to know. 
13. Fine.

**Comment by sujato** [comment]
Just checking, if I want to change the keywords/description, can I do that in base.html? I don't want to break anything …

**Comment by blake-sc** [comment]
If it's meant to be applicable to every page, then you could do it in base.html, something applicable to only one page can be put in a head block for that page (i.e. home.html)

```
{% block head %} 
<meta...>
{% endblock %}
```

That will add the elements to the `<head>`

**Comment by sujato** [comment]
where does this go on the head page? Before or after 
{% extends "base.html" -%}
{% block content %}

**Comment by blake-sc** [comment]
it should come after the {% extends %} and be a sibling of {% block content %} - probably most logical to have the head come before the content (although Jinja doesn't care what order the blocks come in), just make sure there's not already a {% block head %} declared in the template somewhere.

**Comment by sujato** [comment]
okay, I've added it to base.html. We should see our usage skyrocket!
