### ISSUE TITLE
Abhidhamma texts to add

### ISSUE THREAD

**Issue by ghost** [suttacentral/legacy-suttacentral#173]
Just a reminder that more texts and translations should be added.

**Comment by ghost** [comment]
PTS seems to have some english translation that we do not have. 
See http://www.palitext.com/palitext/tipitaka.htm
Discourse on Elements - Dhātukathā 
Designation of Human Types - Puggalapaññatti 
Conditional Relations - Paṭṭhāna
Would it be worth asking them for copyrights and digital files?

**Comment by sujato** [comment]
The only one of these that I'm interested in is the Puggalapannatti, which is already released. the text contains over a hundred quotes or near quotes from suttas, mostly Anguttara. So it would be good to have. the only problem is that the translation is quite archaic, which is why i never pursued it very much. 

The other texts are so Abhidhammic there's little point in a translation. I doubt very much if PTS has digital files for any of these anyway. I'd say just keep an eye out if anyone publishes them.

**Comment by ghost** [comment]
Emailed PTS today.

**Comment by sujato** [comment]
Sorry, what for? i said the only text I'm interested in is the Puggalapannatti, and this is already available.

**Comment by ghost** [comment]
Available ... where? Not on SC it's not. I thought you meant to ask PTS for the digital files if there are any.
I could not find any digital files googling, but maybe you know more.

**Comment by sujato** [comment]
Available as in licence available. 99.9% chance there will not be any digital files. Anyway, let's see what they say.
