### ISSUE TITLE
A couple broken links

### ISSUE THREAD

**Issue by jingoro** [suttacentral/legacy-suttacentral#36]
### From SuttaCentral Bugzilla

Reported By **John Nishinaga** on Tue, 09 Jul 2013 00:39:05 GMT

```
I ran a link checker and found a couple broken links. See below:

ERROR: Could not get external URL: 
http://www.metta.lk/tipitaka/2Sutta-Pitaka/2Majjhima-Nikaya/Majjhima2/051-kandaka-e1.html
  status = 404
{'server': 'Apache', 'vary': 'Accept-Encoding', 'date': 'Mon, 08 Jul 2013 23:50:50 
GMT', 'content-encoding': 'gzip', 'content-length': '20', 'content-type': 
'text/html; charset=iso-8859-1', 'status': '404'}
Translation(seq_nbr=8, lang=ReferenceLanguage(id=1, name='English', abbrev=None, 
code='en'), 
url='http://www.metta.lk/tipitaka/2Sutta-Pitaka/2Majjhima-Nikaya/Majjhima2/051-kandaka-e1.html', 
abstract='English translation of MN 51 from Metta Net. Translator Sister 
Uppalavanna.')
ERROR: Could not get external URL: 
http://www.canonpali.org/tipitaka/suttapitaka/majjhima/mn121.html
  status = 404
{'server': 'Apache', 'vary': 'Accept-Encoding', 'date': 'Mon, 08 Jul 2013 23:50:51 
GMT', 'content-encoding': 'gzip', 'content-length': '20', 'content-type': 
'text/html; charset=iso-8859-1', 'status': '404'}
Translation(seq_nbr=1, lang=ReferenceLanguage(id=2, name='French', abbrev=None, 
code='fr'), url='http://www.canonpali.org/tipitaka/suttapitaka/majjhima/mn121.html', 
abstract='French translation of MN 121 from Accès au Canon Pali (translated from 
English translation on Access to Insight).')
```

Comment 1 by **John Nishinaga** on Tue, 09 Jul 2013 02:02:37 GMT

```
Found one more...

http://www.accesstoinsight.org/tipitaka/sn/sn07/sn07.001.piya.html
  Status: 404
  Response: {'set-cookie': 'PHPSESSID=notn771usi2m3nhq5g5qph7cs7; path=/', 
'expires': 'Thu, 19 Nov 1981 08:52:00 GMT', 'vary': 'Accept-Encoding', 'server': 
'Apache', 'status': '404', 'content-length': '1657', 'content-encoding': 'gzip', 
'date': 'Tue, 09 Jul 2013 01:23:03 GMT', 'content-type': 'text/html', 
'last-modified': 'Sun, 12 Dec 2010 14:57:41 GMT', 'pragma': 'no-cache', 
'cache-control': 'no-store, no-cache, must-revalidate, post-check=0, pre-check=0'}
  Translation: Translation(seq_nbr=2, lang=ReferenceLanguage(id=1, name='English', 
abbrev=None, code='en'), 
url='http://www.accesstoinsight.org/tipitaka/sn/sn07/sn07.001.piya.html', 
abstract='English translation of SN 7.1 from Access to Insight. Translator Piyadassi 
Thera.')
```

**Comment by jhanarato** [comment]
I checked 'external_text.csv'. It still has these links:
This is broken:
http://www.metta.lk/tipitaka/2Sutta-Pitaka/2Majjhima-Nikaya/Majjhima2/051-kandaka-e1.html 
This redirects and works:
http://www.canonpali.org/tipitaka/suttapitaka/majjhima/mn121.html
This is broken:
http://www.accesstoinsight.org/tipitaka/sn/sn07/sn07.001.piya.html

**Comment by sujato** [comment]
This is outstanding for some time. It would be good to run a thorough link check and ensure all are working.

**Comment by ghost** [comment]
I wonder if it is useful to have external links in the drop-down menu with the various languages (italic languages on the bottom of the menu). These lead away from our own page (they are not target="_blank" and are not always helpful. 

For instance, there is a german one (de) to palicanon.com on the menu but the suttas I uploaded on SC itself are from there (or it's sister-site palicanon.de which is actually a copy of palicanon.com) so why do we still need this link? 

Another random example: DN5 - we have the Rhys Davis translation on our site and then there are two more links in italics on the bottom of the menu pointing to the same translation on 2 other sites. 
So what is the policy/rationale behind this?

**Comment by sujato** [comment]
Here's some guidelines for handling these following policies we've worked out.

We should delete all external links that duplicate those on site. 

External links should be target="_blank"

We should retain external links to texts that are alternative translations to the ones on site, except for the metta.lk links. These should be deleted if we have local ones. 

This last point means that all metta.lk links will be deleted when I finish my translation. 

We will have to figure out how to display texts when we have multiple translations locally. In the Translations dropdown, I suggest we have something like:
- en Sujato
- en Bodhi
- en Anandajoti

And so on, listing the translator's name up front.

**Comment by ghost** [comment]
At the moment they are not all target="_blank" - in fact in the drop-down menu with languages I found none that opened in a new tab.

> We should retain external links to texts that are alternative translations to the ones on site, except for  the metta.lk links. These should be deleted if we have local ones.

In this case I have quite a few others, especially from those websites that refused us copyright.

I will have a look at how this whole thing is structured now in the backend and make some suggestions on how to change it within the next week or so.

**Comment by ghost** [comment]
target="_blank" in language dropdown fixed for external links.
Will have a look at all the other issues and external links next.

**Comment by palistudent** [comment]
What does this mean from a practical user's perspective? It's technical jargon Rod nor I understand.
Thanks, John

```
  From: SamaneriVimala <notifications@github.com>
```

 To: suttacentral/suttacentral suttacentral@noreply.github.com 
 Sent: Friday, 17 July 2015, 19:27
 Subject: Re: [suttacentral] A couple broken links (#36)

target="_blank" in language dropdown fixed for external links.
Will have a look at all the other issues and external links next.—

**Comment by sujato** [comment]
Hi John, it just means that links to external sites will open in a new tab; this was previously what happened, but it seems it got messed up when we introduced the dropdown for choosing languages .

**Comment by ghost** [comment]
Metta.lk - there is a broken link on their website - the whole of the Majjhima Nikaya is not available. Do we have a contact person I can write to to make them aware of the problem or shall I just write to metta@mail.metta.lk as is listed on their site?

http://www.canonpali.org/tipitaka/suttapitaka/majjhima/mn121.html redirects to http://www.accesstoinsight.org/tipitaka/mn/mn.121.than.html so it becomes English instead of French. Was Alain not working on all the files from canonpali.org so we have everything on our own server soon?

http://www.accesstoinsight.org/tipitaka/sn/sn07/sn07.001.piya.html seems to have changed from the translation of Ven. Piyadassi to that of Maurice Walsh. So the filename has changed also - I will have a look at it and change it.

I ran check_external_urls.py and found a whole lot more broken links which I will have to go through - many are from metta.lk.

**Comment by sujato** [comment]
Metta.lk goes up and down quite frequently, don't worry about it.

Best contact Alain directly to see how the French stuff is going, I find it hard to remember who's doing what! But as a rule, we should definitely focus on getting stuff on SC rather than maintaining external links.

**Comment by ghost** [comment]
OK. Just removed the two other files that no longer exist and removed all external Kay Zumwinkel MN references because we have that on SC already (Kay Zumwinkel = Ajahn Mettiko).  Will have a run through the rest at some point but not as a priority.
I emailed Alain.

**Comment by ghost** [comment]
In order to make the drop-down language menu a bit more conform, I propose the following:
1. Internal links
   - in alphabetical order of language
   - hoover over the text will give you the name of the translator (if known). (Not "translated by ...." as is now the case for some)
   - in case of multiple links for the same language such as we will have for English, we can either do the same as above (just hoover over the text to see the translator name - this is my preferred option) or as Bhante suggested:
     - en English Sujato
     - en English Bodhi
     - etc.
2. external links
   - in italics and alphabetical order of language but below the internal links (or do you prefer them to be in alphabetical order with the internal links so you have all the translations of one language grouped together?)
   - hoover over the text will give you the name of the translator or external website (not a whole paragraph of text as is now the case)
   - in case of multiple links for the same language (we have this in some places), we can do the same as for the internal links, whichever method we choose there.

Does anybody have any ideas about this?

**Comment by sujato** [comment]
That sounds fine, except I would prefer the shorter "en Sujato" rather than
the redundant "en English Sujato". Hover to get the spelled out language
name.

A number of people have mentioned that we should make translator's names
more prominent. I have been reluctant to display them on the text page, as
I think it is unnecessary, and will fight to the death to preserve every
white pixel on the text pages. But having them visible on the division
pages, etc., would address this issue to some extent. it also lets you skim
the list for what you want. Popups are not very good for touchscreens, and
should be reserved for secondary information.

I would put all the external links at the bottom. many, if not most, of
them will be removed anyway, i.e. the metta.lk ones.

In some cases the translator info is not in the metadata. It would be good
to go through the translated texts and ensure that as many of possible has
this. In some cases it is simple omission, and the translator is mentioned
in the sidebar, but not in the head. In other cases we don't know who the
translator is; for example, in Thai, I am waiting for Dheerayupa to source
some more info about the edition.

O, and BTW "hoover" is a vacuum cleaner!

**Comment by palistudent** [comment]
I agree with all of this.Thanks for your good work, Samaneri.John

```
  From: sujato <notifications@github.com>
```

 To: suttacentral/suttacentral suttacentral@noreply.github.com 
Cc: palistudent palistudent@yahoo.com 
 Sent: Wednesday, 22 July 2015, 9:04
 Subject: Re: [suttacentral] A couple broken links (#36)

That sounds fine, except I would prefer the shorter "en Sujato" rather than
the redundant "en English Sujato". Hover to get the spelled out language
name.

A number of people have mentioned that we should make translator's names
more prominent. I have been reluctant to display them on the text page, as
I think it is unnecessary, and will fight to the death to preserve every
white pixel on the text pages. But having them visible on the division
pages, etc., would address this issue to some extent. it also lets you skim
the list for what you want. Popups are not very good for touchscreens, and
should be reserved for secondary information.

I would put all the external links at the bottom. many, if not most, of
them will be removed anyway, i.e. the metta.lk ones.

In some cases the translator info is not in the metadata. It would be good
to go through the translated texts and ensure that as many of possible has
this. In some cases it is simple omission, and the translator is mentioned
in the sidebar, but not in the head. In other cases we don't know who the
translator is; for example, in Thai, I am waiting for Dheerayupa to source
some more info about the edition.

O, and BTW "hoover" is a vacuum cleaner!

**Comment by ghost** [comment]
Sorry to go on about this but before you go I just want to be absolutely clear that I understand you correctly.

> That sounds fine, except I would prefer the shorter "en Sujato" rather than the redundant "en English Sujato". Hover to get the spelled out language name.

Right now it says "En English". It is not so redundant in the case of all languages, for instance in case of languages with a different script or things like "FI Suomi". I had a look on other sites and they usually exclude the code, just have "English" or "Suomi".
If we have something like "EN Sujato", "EN Bodhi" followed by "DE Deutsch", "FI Suomi" it might be a bit confusing.
So are you saying the dropdown menu would look like (in alphabetical order):
- De
- En Bodhi
- En Sujato
- Fi
- My
- etc ...

And when hovering (with one "o") with the mouse over the text it would say "Deutch", "English", etc.

OR do you mean that the dropdown menu would look like:
- De Hecker
- En Bodhi
- En Sujato
- Fi NameFinishTranslator
- My NameBurmseTranslator
- etc ...

(and the same would be done with the external links at the bottom)

> In some cases the translator info is not in the metadata. It would be good to go through the translated texts and ensure that as many of possible has this. 

Will put it on my to-do list.

**Comment by sujato** [comment]
The latter: we should list all translator's names. If there is no
translator's name, perhaps have the language name, but greyed out.

**Comment by ghost** [comment]
Ok. changed external_text.csv to reflect only the author names but kept the old setup in external_text_old.csv in case we need the info back. 
The rest I will leave up to Blake to do.

**Comment by sujato** [comment]
I think this has broken something? I get the following error when I run invoke server on palilookout 2.0 branch or on master.

```
logger.error("Critical Error: IMM buid failed.", e)
Message: 'Critical Error: IMM buid failed.'
Arguments: (TypeError('Error on line 1161 in table external_text, (Expected 5 arguments, got 7)',),)
```

**Comment by ghost** [comment]
Try again ... there was a rogue comma.

**Comment by sujato** [comment]
Now we're good, thanks
