### ISSUE TITLE
Fonts slowing down site...

### ISSUE THREAD

**Issue by jingoro** [suttacentral/legacy-suttacentral#64]
Currently there are at least 6 webfonts being loaded on the first page landing, for a total of about 500KB. This is pretty hefty! Adding the TharLon (Burmese) font would add another 130KB on top of that. Even on my relatively fast connection, this gives about a 5s+ page load for first landings.

![full-front](https://f.cloud.github.com/assets/21310/1710296/2824995a-612e-11e3-9eb3-602b1c18707b.png)

**Comment by jingoro** [comment]
Running a quick test of disabling all but the Skolar Sutta Web Regular font (and using the default system fonts for the rest) gives much better results, and the look of the page is nearly identical.

![screen shot 2013-12-09 at 3 48 33 pm](https://f.cloud.github.com/assets/21310/1710318/7bf7fc52-612e-11e3-8788-e92c2e35d953.png)

This drops the initial page load to about 2.5s.

**Comment by jingoro** [comment]
My recommendation is:
1. Minimize the number of fonts to the bare minimum. Many of the bold/italic/small caps variants are probably not worth the cost. I personally think we can get away with just loading one font–Skolar Sutta Web Regular–but this may bit extreme. ;-)
2. Convert the logo area into an image to ensure it "looks nice".
3. Write some logic to load more language specific fonts for those pages that explicitly require it. Some tools can help with this like [Webfont Loader](https://developers.google.com/fonts/docs/webfont_loader).

**Comment by sujato** [comment]
The quick answer is a "no" to all but suggestion 3. The choice of fonts is very careful and deliberate, and has been designed so that we can represent the best possible typographical standards. For the first time, due to @font-face and CSS3, we are able to develop typography for the web that is in most respects as good as print. Achieving excellence in typography is one of the basic aspirations of the design. 

Of course I am aware that the fonts are a hit on the page loading; the point is that we do not have images, social media widgets and all the other rubbish that normally clutter up pages. Instead we use the bandwidth to deliver what people actually use, which is the fonts. That is what everyone who looks at our site actually spend their time looking at. And as a result the page load time is actually fairly fast compared to most sites.

When the fonts are properly cached, they should not be a problem: I find, using a wide variety of connections in different countries, that SC is responsive and is often extremely fast.

The area where we can do better is your point three. I have already discussed this with David Brezina, especially when we developed the Vietnamese fonts. In fact the glyphs required for Vietnamese pretty much double the font size, and for 8 fonts that's a fair amount. So the easiest way to speed things up will be to split out the Vietnamese characters and only deliver them when needed. When we first implemented the fonts, we decided not to do this purely for the sake of simplicity: get it going, and optimize later.

Of course, if we are looking at further delivering Burmese and in the future other fonts, we will inevitably need to work out a way to deliver fonts specific for languages. So perhaps that's what we should do at first. If you're working on the  Burmese, then we can implement that. Later we can look at how to apply that for Vietnamese by subsetting the fonts. 

(One reason we were reluctant to mess around with the fonts was that we found it is very difficult to do anything without affecting the hinting. The Skolar family has been hand-hinted, which is one of the reasons why they are so good for us. David even specially hand-hinted the Vietnamese glyphs. Source Sans is also nicely hinted. This is, unfortunately, still necessary because of the low resolution of many screens. In the future times of universal retina displays it will be irrelevant, and we will have a much wider choice of fonts.)

**Comment by jingoro** [comment]
It's fantastic that SC has high-quality fonts and feeling that people care the way things look. That said, many people are using and will continue to be using SC from areas where Internet speed is not fast. The first page loading time is quite important because if a user doesn't see something for the some amount of time (research seems to vary about what that point is), they can leave not only out of frustration or impatience, but thinking the site does not work. From that vantage point, having a relatively fast site is not just a "nice to have," but starts to become functional requirement. So when is that point reached? When is it too slow?

Your perception is important since you're interacting with the larger community about it. My personal feeling is it's fast enough right now. The [RUM scores](https://en.wikipedia.org/wiki/Real_user_monitoring) from NewRelic are also agreeing that SC is currently fast enough.

So given that, I don't think it's worth doing doing any optimizations right now, including splitting up fonts or incorporating fancy font-loading techniques. I've assigned this issue as `nicetohave` for now.

**Comment by sujato** [comment]
Following subsequent discussions with David Brezina and colleagues at Rosetta, we are preparing high quality fonts for several Asian languages: Lumen for Thai and Burmes, Serendip for Sinhala, and Skolar Devanagari for Devanagari. Obviously with several complex scripts like these we cannot deliver them all at the same time, but only when needed. David has developed new tools for more effective subsetting of fonts, so we will work with them to ensure that we deliver only what is necessary. By separating the Vietnamese glyphs we will roughly halve the weight of the Roman fonts.
