### ISSUE TITLE
q class="open"

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#82]
`<q class="open">` is found in some Pali texts, eg pi/ud4.1. It marks up some kind of variant reading, however it creates random quote marks in the text. It is an improper use of the `<q>` tag and should be replaced with something more suitable.

For now I have added `q:before,q:after { content: "";}` to sc.scss. This gets rid of the random quote marks, but doesn't solve the main issue.

**Comment by blake-sc** [comment]
Ah yes, these are residues from the variant note integration process. They are markers indicating where a variant note begins or ends, but the automated process couldn't reconcile them - typically this is due to something funny going on, like the variant note span being across two suttas (starting in one sutta, ending in another). Ideally a human would go through and fix them by turning them into proper variant note markup, and figuring out what to do with the case that made them not automatically reconcilable.

**Comment by ghost** [comment]
Can you be a little bit more specific on what needs to be done with those q tags exactly: change them to span?
`<q class="open" id="note133" title=" upasaṅkamitvā (sabbattha)">. Addasaṃ kho ahaṃ, bhante</q>`
would have to become what? Something like this maybe: ??
`<span class="var" title="upasaṅkamitvā (sabbattha)" id="note133"> Addasaṃ kho ahaṃ, bhante</span>`
I can put it on my to-do list :-)

**Comment by sujato** [comment]
If at the very least they could be changed to span: several times I've copy pasted text and I have these annoying quote marks appear and I'm pulling my hair out and then, oh yeah, it's those little buggers....  again...

**Comment by ghost** [comment]
I'll do it - they will mess up my html-to-tex code when I start working on the pali texts.

**Comment by blake-sc** [comment]
Most of them are cases where the form of the variant reading was non-conformant with what the code expected, a common example is this one:
" etthantare pāṭho syā1-3 potthakesu" or "etthantare pāṭho sī , syā1-3 potthakesu"
which I believe means something like "the reading differs between [mentioned] editions"

That is a non-conformant variant reading, because it is a comment. An actual variant note won't have the trailing text after the "syā1-3", the code knew it wasn't a variant reading from the form, but didn't know what to do with it. It probably needs different handling when generating the variant note popup.

In cases of comments of this kind and similar, you could just put them into span class="var", that would be fine. Ideally the javascript which generates the fancy popups should be updated to handle them gracefully.

Note there are also cases of other things though, essentially the q's contain exceptional variant notes and often non-variant notes such as "notes on variants" instead of "variant notes", but by no mean is that the only exceptional case.

**Comment by ghost** [comment]
I found quite a number with notes inside notes so I can imagine that this caused a problem. I just left it like that for the time being, just changed everything to span class="var". 
You can see all the files changed in git gui - there are not that many so if any of them should not have been done that way, just change it or let me know exactly how it needs to be handled. 
That brings me to a second question to Bhante: how do these notes have to be handled in LaTex????

**Comment by blake-sc** [comment]
Notes inside notes is not a problem, unless it is a case of partial overlap, if one note completely encloses another note (including the case where two notes refer to exactly the same text), it is fine. Partial overlap is problematic, and best dealt with by terminating the first note when the second begins (from context, it is normally obvious to what text span the note refers).
