### ISSUE TITLE
Improve Discourse header integration with SC

### ISSUE THREAD

**Issue by sujato** [suttacentral/legacy-suttacentral#86]
Currently Discourse has the same main title as the main site, which is kind of confusing, and no way to conveniently get to suttacentral.net.

The standard way this is handled on Discourse is like this:

http://discourse.stonehearth.net/

You put an extra div with the main site; that disappears when you scroll down, leaving the main Discourse header.

Another option is this, which places a "return to main site" icon on the right:

https://community.bitnami.com/

But I prefer the former option.

We'd want to do something like this:

![discourse_header](https://cloud.githubusercontent.com/assets/6112010/7547835/ad178ae6-f638-11e4-8e2f-1a5be9857a16.jpg)

**Comment by blake-sc** [comment]
Does discourse have a built in way of doing this?

**Comment by sujato** [comment]
https://meta.discourse.org/t/customization-of-header/5853

**Comment by SamaneriVimala** [comment]
Why not just replace suttacentral-site-title-icon.png with another one like this:
![discoursesc](https://cloud.githubusercontent.com/assets/7444824/11744264/24b26aa0-a00f-11e5-8ee9-ce319201d4de.png)
I don't think I have access to the site - the original logo (suttacentral-site-title-icon.png) is also used in the donation notification email, otherwise it would just be a matter of replacing it.

**Comment by ghost** [comment]
Can I have some login details for the discourse platform so I can have a look.

**Comment by blake-sc** [comment]
I've made you an admin on our Discourse, the one I'm working on at the moment is under admin->customized->css/html->Domain Header

**Comment by SamaneriVimala** [comment]
:-) I already found it and am working on it :-)
Should be pretty easy I think.

**Comment by ghost** [comment]
I made some changes, but used images instead of text as I could not get the text to display as I liked it (something to do with the default settings). 
Discourse seems to have various css settings that are hidden elsewhere and cannot be adapted. It did OK in the preview, but when I added it to the life version, things changed. I could do a bit more work to look into this and find out what those settings are exactly and override them, but I'm afraid that if Discourse upgrades this might be reset.
I would also like to see what it does on a mobile phone and adapt those settings, but my phone is too old for that. But again, Discourse is limited and there are many types of mobile phones so not sure what that would do.

**Comment by blake-sc** [comment]
By the way the "Discuss & Discover" image is a PNG but has JPG compression artifacts, it'd be nice if it were a clean PNG. What is the font used?

**Comment by ghost** [comment]
Ha, you caught me out :-)
It is a screenshot and I have no idea what the font is. Something I still
have to do indeed. Leave it to me and I will take care.
Or Bhante ... do you know what the font is - saves me searching for it.

**Comment by ghost** [comment]
I've now changed it to a png in Skolar PE Italic - fairly similar but not entirely the same. So Bhante - is this font OK or does it need changing. Also cleaned up the filenames.
Colour also looks slightly different. I used #005179.
